<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  ':name assigned.' => ':name 已指派',
  'Add' => '添加',  
  'Create' => '录入',  
  'Data' => '数据',
  'Delete' => '删除',
  'Description' => '描述',
  'Item' => '项目',
  'Modules' => '模块',
  'Name' => '名称',
  'Remove' => '删除',
  'Revoke' => '撤销',
  'Save' => '保存',  
  'Select all' => '全选',
  'Select none' => '不选',  
  'Update' => '修改',
  'Search' => '搜索',

  'Admin' => '管理',
  'View' => '浏览',
  'Action' => '操作',
  'Create New' => '录入新的',

  'Return' => '返回',
  'Reset' => '重置',
  'Refresh' => '刷新',
  
  'More' => '更多', 

  'Manages' => '帐号',
  'Clientele' => '客户',
  'Clienteles' => '客户',
  'ContactpPrson' => '联系人',
  'Contactp Prson' => '联系人',
  'Contactp Prsons' => '联系人',

  'Contact' => '联系记录',
  'Contacts' => '联系记录',

  'AddressBook' => '通讯录',
  'AddressBooks' => '通讯录',
  'Address Book' => '通讯录',
  'Address Books' => '通讯录',

  'Address Groups' => '部门',
  'AddressGroups' => '部门', 
 );