<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  ':name assigned.' => ':name 已指派',
  'Error'=>'错误',
  'Add' => '添加',  
  'Create' => '新建',  
  'Entering' => '录入',  
  'Data' => '数据',
  'Delete' => '删除',
  'Description' => '描述',
  'Item' => '项目',
  'Log' => '日志',
  'Modules' => '模块',
  'Name' => '名称',
  'Remove' => '删除',
  'Revoke' => '撤销',
  'Save' => '保存',  
  'Select all' => '全选',
  'Select none' => '不选',  
  'Update' => '修改',
  'Search' => '搜索',

  'Admin' => '管理',
  'View' => '浏览',
  'Action' => '操作',
  'Create New' => '添加新的',
  'Restore' => '还原',
  'Recycle' => '回收站',
  'Deletes' => '彻底删除',

  'Return' => '返回',
  'Reset' => '重置',
  'Refresh' => '刷新',

  'Setting' => '设置',
  
  'More' => '更多', 
  'Detail' => '明细', 

  'AdminLog' => '网站日志',
  'Manage' => '用户',
  'Manages' => '用户',
  'Clientele' => '客户',
  'Clienteles' => '客户',
  'ContactpPrson' => '联系人',
  'Contactp Prson' => '联系人',
  'Contactp Prsons' => '联系人',

  'Contact' => '联系记录',
  'Contacts' => '联系记录',

  'AddressBook' => '通讯录',
  'AddressBooks' => '通讯录',
  'Address Book' => '通讯录',
  'Address Books' => '通讯录',

  'Address Groups' => '部门',
  'AddressGroups' => '部门', 

  'Events' => '提醒', 

  'Product' => '产品',
  'Products' => '产品',

  'Purchase' => '入库',
  'Sell' => '出库',
  'Stocks' =>'结存明细',

  'bill' => '单',
  'Print' => '打印',
  'Import' => '导入',
  'Volume' => '生成',
  'Close' => '关闭',
  'Affirm' => '确认',

  'Purchase enterprise' => '来源',
  'Sell enterprise' => '客户',
  'enterprise' => '单位名称',

  'Purchase typeid' => '入库方式',
  'Sell typeid' => '出库方式',
  
  'Advanced Search' => '详细搜索',
  'Illegal operation' => '非法操作！', 
  'TakType' => '分类',  


  'Test Memebers' => '测试帐号',
  'TestMemeber' => '测试帐号',

  'Test Logs' => '测试帐号日志',
  'TestLogs' => '测试帐号日志',

  'Permissions' => '权限',

  'View Roles' => '角色权限介绍',
 );


